# Generated by Django 6.0.5 on 2026-05-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.category', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='book',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Premium'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='reading_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Время чтения'),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_books', to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Есть Premium-издание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена Standard'),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Описание картинки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Изображение книги',
                'verbose_name_plural': 'Изображения книги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
