# Generated by Django 6.0.5 on 2026-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_categories_book_premium_price_book_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите только число, например 12, 16 или 18. Плюс на сайте добавится автоматически.', null=True, verbose_name='Возрастной рейтинг'),
        ),
    ]
